export default class ActionType{
    static ACTION_BOOK_SET_NOW_PIC='ACTION_BOOK_SET_NOW_PIC'
    static ACTION_BOOK_SET_NOW_BOOKID='ACTION_BOOK_SET_NOW_BOOKID'
    static ACTION_BOOK_SET_NOW_TITLE='ACTION_BOOK_SET_NOW_TITLE'
    static ACTION_BOOK_SET_FINISHTIME='ACTION_BOOK_SET_FINISHTIME'
    static ACTION_BOOK_SET_HASFINISHIEDNUM='ACTION_BOOK_SET_HASFINISHIEDNUM'
    static ACTION_BOOK_SET_NOWTOTALCOUNT='ACTION_BOOK_SET_NOWTOTALCOUNT'
    static ACTION_BOOK_SET_STUDYBOOKLIST='ACTION_BOOK_SET_STUDYBOOKLIST'
    static ACTION_BOOK_SET_ISLOADINGSTUDYBOOKLIST='ACTION_BOOK_SET_ISLOADINGSTUDYBOOKLIST'
    static ACTION_BOOK_SET_ISLOADINGNOWSTUDYBOOK='ACTION_BOOK_SET_ISLOADINGNOWSTUDYBOOK'
    static ACTION_BOOK_SET_STUDYBOOkLISTCOUNT='ACTION_BOOK_SET_STUDYBookLISTCOUNT'
    static ACTION_BOOK_SET_STUDYBOOkLISTPAGENUM='ACTION_BOOK_SET_STUDYBOOkLISTPAGENUM'
    static ACTION_BOOK_SET_ISLOADEDSTUDYBOOKLIST='ACTION_BOOK_SET_isLoadedStudyBookList'
    static ACTION_BOOK_SET_ISLOADEDNOWSTUDYBOOK='ACTION_BOOK_SET_isLoadedNowStudyBook'

}